import 'package:flutter/material.dart';

/// The Material icon closest to a Font Awesome icon a forum chose for a
/// category (Discourse's `icon` category style), or null when there is no
/// good match. The app does not carry Font Awesome, so a category whose
/// icon is not here keeps its colour square.
///
/// Discourse names icons as Font Awesome 6 does (`circle-question`), with
/// some of its own (`discourse-bell-exclamation`) and some older FA5 names
/// still in use (`question-circle`); a `far-`/`fab-`/`fas-` prefix picks a
/// Font Awesome style and is ignored here.
IconData? materialIconForDiscourseIcon(String? name) {
  if (name == null) return null;
  var key = name.trim().toLowerCase();
  for (final prefix in const ['far-', 'fab-', 'fas-', 'fa-']) {
    if (key.startsWith(prefix)) key = key.substring(prefix.length);
  }
  return _icons[key];
}

const Map<String, IconData> _icons = {
  // Questions, help, information
  'question': Icons.help_outline,
  'circle-question': Icons.help_outline,
  'question-circle': Icons.help_outline,
  'life-ring': Icons.support_outlined,
  'circle-info': Icons.info_outline,
  'info-circle': Icons.info_outline,
  'info': Icons.info_outline,
  'lightbulb': Icons.lightbulb_outline,
  // Talk
  'comment': Icons.chat_bubble_outline,
  'comments': Icons.forum_outlined,
  'comment-dots': Icons.sms_outlined,
  'bullhorn': Icons.campaign_outlined,
  'megaphone': Icons.campaign_outlined,
  'microphone': Icons.mic_none,
  'podcast': Icons.podcasts,
  'envelope': Icons.mail_outline,
  'bell': Icons.notifications_none,
  'discourse-bell-exclamation': Icons.notification_important_outlined,
  'bell-exclamation': Icons.notification_important_outlined,
  'newspaper': Icons.newspaper,
  'rss': Icons.rss_feed,
  // Problems and status
  'bug': Icons.bug_report_outlined,
  'triangle-exclamation': Icons.warning_amber,
  'exclamation-triangle': Icons.warning_amber,
  'circle-exclamation': Icons.error_outline,
  'check': Icons.check,
  'circle-check': Icons.check_circle_outline,
  'square-check': Icons.check_box_outlined,
  'list': Icons.list,
  'list-ul': Icons.list,
  'list-check': Icons.checklist,
  'tasks': Icons.checklist,
  'flag': Icons.flag_outlined,
  'shield': Icons.shield_outlined,
  'shield-halved': Icons.shield_outlined,
  'lock': Icons.lock_outline,
  // Making things
  'code': Icons.code,
  'terminal': Icons.terminal,
  'plug': Icons.power_outlined,
  'puzzle-piece': Icons.extension_outlined,
  'palette': Icons.palette_outlined,
  'paintbrush': Icons.brush_outlined,
  'brush': Icons.brush_outlined,
  'pen': Icons.edit_outlined,
  'pencil': Icons.edit_outlined,
  'pen-to-square': Icons.edit_note,
  'wand-magic-sparkles': Icons.auto_fix_high,
  'wand-magic': Icons.auto_fix_high,
  'magic': Icons.auto_fix_high,
  'gear': Icons.settings_outlined,
  'gears': Icons.settings_outlined,
  'cog': Icons.settings_outlined,
  'cogs': Icons.settings_outlined,
  'wrench': Icons.build_outlined,
  'screwdriver-wrench': Icons.build_outlined,
  'tools': Icons.build_outlined,
  'hammer': Icons.handyman_outlined,
  'cube': Icons.view_in_ar_outlined,
  'cubes': Icons.widgets_outlined,
  'box': Icons.inventory_2_outlined,
  'box-archive': Icons.inventory_2_outlined,
  'archive': Icons.inventory_2_outlined,
  'rocket': Icons.rocket_launch_outlined,
  'flask': Icons.science_outlined,
  'microchip': Icons.memory,
  'robot': Icons.smart_toy_outlined,
  'server': Icons.dns_outlined,
  'database': Icons.storage,
  'cloud': Icons.cloud_outlined,
  'mobile': Icons.smartphone,
  'mobile-screen': Icons.smartphone,
  'mobile-screen-button': Icons.smartphone,
  'laptop': Icons.laptop,
  'laptop-code': Icons.laptop,
  'desktop': Icons.computer,
  'computer': Icons.computer,
  // Reading and learning
  'book': Icons.menu_book_outlined,
  'book-open': Icons.menu_book_outlined,
  'file': Icons.description_outlined,
  'file-lines': Icons.description_outlined,
  'file-alt': Icons.description_outlined,
  'graduation-cap': Icons.school_outlined,
  'chalkboard-user': Icons.school_outlined,
  'language': Icons.translate,
  'globe': Icons.public,
  'earth-americas': Icons.public,
  'earth-europe': Icons.public,
  // People
  'user': Icons.person_outline,
  'users': Icons.groups_outlined,
  'user-group': Icons.groups_outlined,
  'people-group': Icons.groups_outlined,
  'handshake': Icons.handshake_outlined,
  'handshake-angle': Icons.handshake_outlined,
  'hands-helping': Icons.handshake_outlined,
  'heart': Icons.favorite_border,
  'star': Icons.star_outline,
  'trophy': Icons.emoji_events_outlined,
  'award': Icons.military_tech_outlined,
  'medal': Icons.military_tech_outlined,
  'gift': Icons.card_giftcard,
  'face-smile': Icons.sentiment_satisfied_alt,
  'smile': Icons.sentiment_satisfied_alt,
  // Things and places
  'calendar': Icons.calendar_today_outlined,
  'calendar-days': Icons.calendar_month_outlined,
  'calendar-alt': Icons.calendar_month_outlined,
  'clock': Icons.schedule,
  'house': Icons.home_outlined,
  'home': Icons.home_outlined,
  'location-dot': Icons.place_outlined,
  'map-marker': Icons.place_outlined,
  'map': Icons.map_outlined,
  'car': Icons.directions_car_outlined,
  'plane': Icons.flight,
  'bicycle': Icons.pedal_bike,
  'camera': Icons.photo_camera_outlined,
  'image': Icons.image_outlined,
  'video': Icons.videocam_outlined,
  'film': Icons.movie_outlined,
  'music': Icons.music_note,
  'headphones': Icons.headphones,
  'gamepad': Icons.sports_esports_outlined,
  'dice': Icons.casino_outlined,
  'shopping-cart': Icons.shopping_cart_outlined,
  'cart-shopping': Icons.shopping_cart_outlined,
  'store': Icons.storefront_outlined,
  'money-bill': Icons.payments_outlined,
  'dollar-sign': Icons.attach_money,
  'coins': Icons.toll_outlined,
  'briefcase': Icons.work_outline,
  'chart-line': Icons.show_chart,
  'chart-bar': Icons.bar_chart,
  'chart-pie': Icons.pie_chart_outline,
  'tag': Icons.sell_outlined,
  'tags': Icons.sell_outlined,
  'link': Icons.link,
  'leaf': Icons.eco_outlined,
  'seedling': Icons.eco_outlined,
  'tree': Icons.park_outlined,
  'paw': Icons.pets,
  'fire': Icons.local_fire_department_outlined,
  'bolt': Icons.bolt,
  'sun': Icons.wb_sunny_outlined,
  'moon': Icons.dark_mode_outlined,
};
